line.bot:
  channel-token:  "BacdXVr8sGiBO86Vou5SRrby8sQGe+NvdbJJL/OOKeqj35w+yj3rj7c1nWT2ZdUBOozhv1TuqpeUmKIeZRNqxH118T7ZwlYPjaYRqOxlE9X50RVVIepi4u8cYM9SkahUmW7WzqCFbkBrpoHNUOnwQAdB04t89/1O/w1cDnyilFU="
  channel-secret: "87d16ebbebb0ac766375addecd8b629c"
  handler.path: /callback
